### ISSUE TITLE
Error: Multiple commands produce

### ISSUE THREAD

**Issue by Skipperlla** [margelo/react-native-filament#279] opened 2024-10-16 16:22 UTC
<img width="889" alt="Screenshot 2024-10-16 at 19 16 36" src="https://github.com/user-attachments/assets/842f2fa2-56b6-4d82-b9a0-48e5836f6e72">

I get this error when I try to build the application just ios

## metro.config.js
```js
const { getDefaultConfig, mergeConfig } = require("expo/metro-config");
const defaultConfig = getDefaultConfig(__dirname);

/**
 * Metro configuration
 * https://metrobundler.dev/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */

defaultConfig.resolver.sourceExts.push("mjs");
defaultConfig.resolver.sourceExts.push("cjs");

const config = {
  resolver: {
    assetExts: [...(defaultConfig.resolver?.assetExts || []), "glb"],
  },
};

module.exports = mergeConfig(defaultConfig, config);
```

## babel.config.js
```js
module.exports = {
  presets: ["module:metro-react-native-babel-preset"],
  plugins: [
     react-native-worklets-core/plugin,
    ["react-native-reanimated/plugin", { processNestedWorklets: true }],
  ],
};

```
### These are the new depedencies I just installed
<img width="563" alt="Screenshot 2024-10-16 at 19 22 07" src="https://github.com/user-attachments/assets/391dc9a9-365d-4c3f-819b-3cdb1e1a8c44">

**Comment by hannojg** [comment] 2024-10-17 06:59
Duplicate of: 

- https://github.com/margelo/react-native-filament/issues/251

**Closed by hannojg** 2024-10-17 06:59 UTC
